apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricalgo-bot
  namespace: cricalgo-staging
  labels:
    app: cricalgo-bot
    component: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cricalgo-bot
  template:
    metadata:
      labels:
        app: cricalgo-bot
        component: bot
    spec:
      containers:
      - name: bot
        image: cricalgo/bot:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cricalgo-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: cricalgo-secrets
              key: REDIS_URL
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: cricalgo-secrets
              key: TELEGRAM_BOT_TOKEN
        - name: TELEGRAM_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: cricalgo-secrets
              key: TELEGRAM_WEBHOOK_URL
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: cricalgo-secrets
              key: WEBHOOK_SECRET
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: cricalgo-secrets
              key: SENTRY_DSN
              optional: true
        envFrom:
        - configMapRef:
            name: cricalgo-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: bot-logs
          mountPath: /app/logs
      volumes:
      - name: bot-logs
        emptyDir: {}
      restartPolicy: Always
