apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricalgo-worker
  namespace: cricalgo-staging
  labels:
    app: cricalgo-worker
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cricalgo-worker
  template:
    metadata:
      labels:
        app: cricalgo-worker
        component: worker
    spec:
      containers:
      - name: worker
        image: cricalgo/worker:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cricalgo-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: cricalgo-secrets
              key: REDIS_URL
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapRef:
              name: cricalgo-config
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapRef:
              name: cricalgo-config
              key: CELERY_RESULT_BACKEND
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: cricalgo-secrets
              key: SENTRY_DSN
              optional: true
        envFrom:
        - configMapRef:
            name: cricalgo-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /worker_health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: worker-logs
          mountPath: /app/logs
      volumes:
      - name: worker-logs
        emptyDir: {}
      restartPolicy: Always
