apiVersion: v1
kind: Secret
metadata:
  name: cricalgo-secrets
  namespace: cricalgo-staging
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vcG9zdGdyZXM6cGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZToyNTQzMi9jcmljYWxnbw==
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkvMA==
  JWT_SECRET_KEY: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  WEBHOOK_SECRET: eW91ci13ZWJob29rLXNlY3JldA==
  # Add these values from your environment
  # TELEGRAM_BOT_TOKEN: <base64-encoded-token>
  # TELEGRAM_WEBHOOK_URL: <base64-encoded-url>
  # SENTRY_DSN: <base64-encoded-dsn>
