groups:
- name: cricalgo.rules
  rules:
  - alert: HTTPHighP95
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 4
    for: 5m
    labels: { severity: warning }
    annotations:
      summary: "High HTTP p95 latency (>4s)"

  - alert: HTTPHighAvg
    expr: (sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))) > 1.0
    for: 5m
    labels: { severity: warning }
    annotations:
      summary: "High HTTP average latency (>1s)"

  - alert: HighErrorRate
    expr: (sum(rate(http_requests_total{code=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))) > 0.01
    for: 2m
    labels: { severity: critical }
    annotations:
      summary: "High HTTP 5xx error rate (>1%)"

  - alert: CeleryQueueDepthHigh
    expr: avg_over_time(celery_queue_length[5m]) > 50
    for: 5m
    labels: { severity: warning }
    annotations:
      summary: "High Celery queue depth"