name: Smoke Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Test environment'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - staging

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Start test services
      run: |
        docker-compose -f docker-compose.test.yml up -d --build
    
    - name: Wait for services
      run: |
        echo "Waiting for services to be ready..."
        sleep 30
    
    - name: Run smoke test
      run: |
        python scripts/smoke_test.py
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5433/cricalgo_test
        REDIS_URL: redis://localhost:6380/1
        WEBHOOK_SECRET: test-secret-key
        SEED_ADMIN_USERNAME: admin
        SEED_ADMIN_EMAIL: admin@cricalgo.com
        SEED_ADMIN_PASSWORD: admin123
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: smoke-test-results
        path: artifacts/
    
    - name: Cleanup
      if: always()
      run: |
        docker-compose -f docker-compose.test.yml down -v
